services:
  medilogic:
    build: .
    ports:
      - "8000:8000"
    environment:
      DEBUG: "False"
      ALLOWED_HOSTS: "*"
      API_URL: "http://127.0.0.1:8001/consulta"
      SECRET_KEY: "local-dev-secret-key"
